# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f5d2438301edd2afa66d804dceb266b75de12e44cd7be722f27af0a19e5558edf64a287e019a6fd4ad5e18aabc3da049d6cae60537397dd609b44d40b79ecb0

test:
  secret_key_base: 486b1d9dedf99e9f6d812e08dc5beefb2db88b97b5396134caf8eae95e4e0d7bd1b6bc00a54bdbd4fe240644df21508fec908915fba3afa8d5d390c1e55c3654

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
